//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Order = new HashSet<Order>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
